apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
  namespace: spark
spec:
  selector:
    app: spark
    role: master
  ports:
    - protocol: TCP
      port: 7077
      targetPort: 7077
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-service
  namespace: spark
spec:
  selector:
    app: spark
    role: worker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
